### ISSUE TITLE
investigate single failing test case

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-client#100]
I think we can fix the single test case that's failing with `yarn test -u`, which updates the snapshot we have. If this is the ideal fix, I would like to contribute it.

<details>
<summary>The same, sole test case fails on two different devices I tried.</summary>

```
 FAIL  test/API.spec.ts (26.443 s)
  API
    User
      ✓ should get user (1720 ms)
      ✓ should get a users data (2248 ms)
    Pack
      ✓ should get pack (649 ms)
      ✓ should get pack data (1829 ms)
    Sound
      ✓ should get sound (763 ms)
      ✓ should get sound data (2461 ms)
    Search
      ✓ should text search (1097 ms)
      ✕ should perform combined search (11014 ms)
      ✓ should perform content search (912 ms)
    Auth
      ○ skipped should go through oauth process
      ○ skipped should get me
      ○ skipped should get pending sounds

  ● API › Search › should perform combined search

    expect(received).toMatchSnapshot()

    Snapshot name: `API Search should perform combined search 1`

    - Snapshot  - 1
    + Received  + 1

      Object {
    -   "more": "http://freesound.org/apiv2/search/combined/?&query=&filter=tag:loop&target=rhythm.bpm:120&cs_lcvidp=41",
    +   "more": "http://freesound.org/apiv2/search/combined/?&query=&filter=tag:loop&target=rhythm.bpm:120&cs_lcvidp=44",
      }

      110 |       });
      111 |       expect(result).toBeTruthy();
    > 112 |       expect(removeVariableProperties(result)).toMatchSnapshot();
          |                                                ^
      113 |     });
      114 | 
      115 |     it("should perform content search", async () => {

      at Object.<anonymous> (test/API.spec.ts:112:48)

 › 1 snapshot failed.
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 skipped, 8 passed, 12 total
Snapshots:   1 failed, 10 passed, 11 total
Time:        26.641 s
Ran all test suites.
```
</details>

<details>
<summary>This is also the test case that failed on the most recent commit to this repository at the time of this writing.</summary>
<br />

From  https://github.com/amilajack/freesound-client/runs/2393744538:

![Screen Shot 2021-04-21 at 8 49 11 AM](https://user-images.githubusercontent.com/43425812/115583114-735d3780-a27e-11eb-9a3e-60c529785864.png)
</details>

**Comment by amilajack** [comment]
Updating the snapshots would work but unfortunately it isn't a good long term solution which would mock the network requests. See https://www.leighhalliday.com/mock-fetch-jest

**Comment by hamirmahal** [comment]
I've been taking a look at this and I think using [`const fetch = nodeFetch;` on line 16 of `index.ts`](https://github.com/amilajack/freesound-client/blob/f6132400e5d36c5656fbda77391982af5f9304ac/index.ts#L16) makes the above approach not work. Is it possible to use the approach you mentioned with `nodeFetch`?

**Comment by amilajack** [comment]
You'll need to deviate a bit from the article. You'd need to mock the `node-fetch` dep. See these docs: https://jestjs.io/docs/mock-functions#mocking-modules

**Comment by hamirmahal** [comment]
For anyone reading in this future who wants to know how to mock `node-fetch`, I found https://jestjs.io/docs/bypassing-module-mocks very helpful.
