### ISSUE TITLE
re-enable oauth in browser environment

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-client#52]
## Re-enable these lines
* https://github.com/amilajack/freesound-client/commit/295f624da734566fa3455cfb398d6f3d7e487ea0#diff-ed009b6b86b017532ef0489c77de5100L373
* https://github.com/amilajack/freesound-client/commit/295f624da734566fa3455cfb398d6f3d7e487ea0#diff-ed009b6b86b017532ef0489c77de5100L273

**Comment by hamirmahal** [comment]
I was looking through this repository and saw this issue. Do we still need to make these changes?

**Comment by amilajack** [comment]
I think we might've already made these changes so I'll close this￼
